# Generated by Django 4.1.1 on 2022-12-04 18:32

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0002_entry_historicalentry'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), name='title_unique'),
        ),
    ]
