# Generated by Django 4.1.1 on 2022-12-09 07:26

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0002_alter_historicalimage_name_alter_image_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entry',
            name='title_unique',
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), name='title_unique', violation_error_message='A page with that title already exists'),
        ),
    ]
