# Generated by Django 4.1.1 on 2022-12-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0003_remove_entry_title_unique_entry_title_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='talk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historicalentry',
            name='talk',
            field=models.TextField(null=True),
        ),
    ]
